Update sync_fork.yml

diff --git a/.github/workflows/sync_fork.yml b/.github/workflows/sync_fork.yml
--- a/.github/workflows/sync_fork.yml
+++ b/.github/workflows/sync_fork.yml
@@ -16,6 +16,7 @@ jobs:
       uses: actions/checkout@v2
       with:
         fetch-depth: 0 # Fetch all history for all branches and tags.
+        ref: gh-pages
 
     - name: Configure Git
       run: |
@@ -23,13 +24,16 @@ jobs:
         git config user.email "guy.duer@firebolt.io"
 
     - name: Add remote upstream
-      run: git remote add upstream https://github.com/firebolt-db/godocs.git
+      run: git remote add upstream https://github.com/firebolt-db/godocs.git || true
+      # The '|| true' ensures that the step doesn't fail if the remote already exists
 
     - name: Fetch changes from upstream
       run: git fetch upstream
 
     - name: Merge changes from upstream/main to main
       run: |
-        git checkout gh-pages
-        git merge upstream/gh-pages
-        git push origin gh-pages
+        git merge upstream/gh-pages --strategy-option theirs
+        # Using '--strategy-option theirs' to resolve conflicts by favoring upstream changes
+
+    - name: Push changes
+      run: git push origin gh-pages
